name=SimpleLCDMenu
version=1.0.0
author=tpignol
maintainer=tpignol
sentence=Menu system for LCD 16x2 / 20x4 with PCF8575 keypad support.
paragraph=Compatible with LCD_HD44780_PCF8575 and Keypad_PCF8575.
category=Display
architectures=*
